
-- ================================================================
-- SUPABASE - Régua de Cobrança | Exceções + Histórico
-- Execute este script no SQL Editor do seu projeto Supabase.
-- ================================================================

create extension if not exists pgcrypto;

create table if not exists public.admin_users (
    user_id uuid primary key references auth.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

create table if not exists public.excecoes_calendario (
    id uuid primary key default gen_random_uuid(),
    original_date date not null,
    new_date date not null,
    event_title text not null,
    vencimento_original text,
    tipo text not null default 'bloqueio',
    categoria text not null default 'bloqueio',
    descricao text,
    motivo text not null,
    ativo boolean not null default true,
    created_by uuid not null references auth.users(id),
    created_at timestamptz not null default now()
);

create table if not exists public.historico_alteracoes (
    id bigint generated by default as identity primary key,
    excecao_id uuid,
    acao text not null,
    detalhes text,
    created_by uuid references auth.users(id),
    created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.excecoes_calendario enable row level security;
alter table public.historico_alteracoes enable row level security;

-- Helper seguro: identifica se o usuário autenticado é administrador.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.admin_users
        where user_id = auth.uid()
    );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "admin_users_select_self" on public.admin_users;
create policy "admin_users_select_self"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "excecoes_public_read" on public.excecoes_calendario;
create policy "excecoes_public_read"
on public.excecoes_calendario for select
to anon, authenticated
using (ativo = true);

drop policy if exists "excecoes_admin_insert" on public.excecoes_calendario;
create policy "excecoes_admin_insert"
on public.excecoes_calendario for insert
to authenticated
with check (public.is_admin() and created_by = auth.uid());

drop policy if exists "excecoes_admin_update" on public.excecoes_calendario;
create policy "excecoes_admin_update"
on public.excecoes_calendario for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "excecoes_admin_delete" on public.excecoes_calendario;
create policy "excecoes_admin_delete"
on public.excecoes_calendario for delete
to authenticated
using (public.is_admin());

drop policy if exists "historico_admin_read" on public.historico_alteracoes;
create policy "historico_admin_read"
on public.historico_alteracoes for select
to authenticated
using (public.is_admin());

-- Histórico automático de INSERT/UPDATE/DELETE.
create or replace function public.registrar_historico_excecao()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_id uuid;
    v_acao text;
    v_detalhes text;
begin
    if (tg_op = 'DELETE') then
        v_id := old.id;
        v_acao := 'Exceção excluída';
        v_detalhes := format('%s: %s → %s | Motivo: %s',
            old.event_title, old.original_date, old.new_date, old.motivo);
    elsif (tg_op = 'UPDATE') then
        v_id := new.id;
        v_acao := 'Exceção alterada';
        v_detalhes := format('%s: %s → %s | Motivo: %s',
            new.event_title, new.original_date, new.new_date, new.motivo);
    else
        v_id := new.id;
        v_acao := 'Exceção criada';
        v_detalhes := format('%s: %s → %s | Motivo: %s',
            new.event_title, new.original_date, new.new_date, new.motivo);
    end if;

    insert into public.historico_alteracoes
        (excecao_id, acao, detalhes, created_by)
    values
        (v_id, v_acao, v_detalhes, auth.uid());

    return coalesce(new, old);
end;
$$;

drop trigger if exists trg_historico_excecao on public.excecoes_calendario;
create trigger trg_historico_excecao
after insert or update or delete on public.excecoes_calendario
for each row execute function public.registrar_historico_excecao();

-- ================================================================
-- Depois de criar o primeiro usuário no Authentication > Users,
-- execute UMA VEZ, trocando o UUID abaixo:
--
-- insert into public.admin_users (user_id)
-- values ('UUID_DO_USUARIO_DA_SUA_CHEFE');
-- ================================================================
